routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::get('/price', function () {
    return view('prices/price');
});
Route::post('/', 'ContactController@postContact')->name('contact.send');

Route::resource('users','UserController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'phone', 'email',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Mail;
use App\Mail\ContactMail;

class ContactController extends Controller
{
    //
    public function postContact(Request $request){
        /* dd($request); */
        $fields = $request->validate([
            'name' => 'required|max:50',
            'email' => 'required|email',
            'subject' => 'required|max:50',
            'bodyMessage' => 'required'
        ]);
        Mail::to('stac.usa@sucessotrading.com')->send(new ContactMail($fields));
        
        return back()->withInput();
      /*   return redirect()->route('/'); */
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::latest()->paginate(5);
  
        return view('users.index',compact('users'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'phone' => 'required',
            'email' => 'required',
        ]);
  
        User::create($request->all());
   
        return redirect()->route('users.index')
                        ->with('success','User created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/contact/email.blade.php
<h1>Message Received</h1>

<ul>
    <li class="">Name: {{ $name }}</li>
    <li class="">Email: {{ $email }}</li>
    <li class="">Subject: {{ $subject }}</li>
    <li class="">Message: {{ $bodyMessage }}</li>
</ul>

resources/views/home.blade.php
@extends('layout.template')

@section('title','Sucesso Trading')

@section('content') 
<!--Main Layout-->
<div id="home" class="bg-main">
  @include('main._includes.home')
    <main>
      <!---about-->
        @include('main._includes.about')
      <!---scn-->
    </main>
    @include('main._includes.scn')
      <!---contact-->
      @include('main._includes.contact')
</div>
<!---end bg-main-->    
@endsection

resources/views/layout/_includes/footer.blade.php
<!-- Footer -->
<footer class="page-footer font-small indigo">

<!-- Footer Links -->
<div class="container">
    <!-- Grid row-->
    <div class="row d-flex text-center justify-content-center pt-5">
        <img class="logo-footer" src="<?php echo asset('img/logo.svg')?>">
    </div>
    <!-- Grid row-->
    <div class="row text-center d-flex justify-content-center mb-3">
        <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar ">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-center " id="navbarSupportedContent">
                    <ul class="nav ">
                        <li class="nav-item ">
                            <a id="id_home" class="nav-link scroll active " href="#home">Home</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link scroll product" href="#product">Produto</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link scroll support" href="#support">Suporte</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link plans" href="#plans" data-toggle="modal"
                                data-target="#plansModal">Planos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <hr class="rgba-white-light" style="margin: 0 15%;">
    <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">
    <center style="margin-top: 15px;"><span id="siteseal">
            <script async type="text/javascript"
                src="https://seal.godaddy.com/getSeal?sealID=f585IyGP9ZBpdKdcresuaoUsexOuzPjiTfxasY3Ri4yGjRjRu4ljrt8JzSKf"></script>
            </span></center>
</div>
<!-- Copyright -->
<div class="footer-copyright text-white text-center py-3">© 2019 ALL RIGHTS RESERVED</a>
</div>
<!-- Copyright -->

</footer>
<!-- Footer -->

	
<!-- Large modal -->
@include('main._includes.modal')

<!--plansModal -->
@include('main._includes.modal_plans')

<!-- JavaScript -->
<script src="https://code.jquery.com/jquery-1.11.3.min.js" crossorigin="anonymous"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
crossorigin="anonymous"></script> -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
crossorigin="anonymous"></script>
<script src="<?php echo asset('js/all.js')?>"></script>

</body>

</html>

resources/views/layout/_includes/top.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Barlow&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="57x57" href="../img/icon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="../img/icon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="../img/icon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="../img/icon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="../img/icon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="../img/icon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="../img/icon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="../img/icon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/icon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="../img/icon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/icon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="../img/icon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/icon/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <meta http-equiv="Content-Language" content="pt-br, en, es">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?php echo asset('css/all.css')?>">

    <!-- Search Engine -->
    <meta name="description" content="Sucesso Trading é uma empresa especializada em locação de criptomoedas com foco no rendimento de capital com transparência, agilidade e eficácia a todo usuário que utiliza o serviço de locação de nossas moedas (SCN).">
    <meta name="image" content="http://sucessotrading.com/img/logo.svg">
    <!-- Schema.org for Google -->
    <meta itemprop="name" content="Success Trading">
    <meta itemprop="description" content="Sucesso Trading é uma empresa especializada em locação de criptomoedas com foco no rendimento de capital com transparência, agilidade e eficácia a todo usuário que utiliza o serviço de locação de nossas moedas (SCN).">
    <meta itemprop="image" content="http://sucessotrading.com/img/logo.svg">
    <!-- Open Graph general (Facebook, Pinterest & Google+) -->
    <meta name="og:title" content="Success Trading">
    <meta name="og:description" content="Sucesso Trading é uma empresa especializada em locação de criptomoedas com foco no rendimento de capital com transparência, agilidade e eficácia a todo usuário que utiliza o serviço de locação de nossas moedas (SCN).">
    <meta name="og:image" content="http://sucessotrading.com/img/logo.svg">
    <meta name="og:url" content="http://sucessotrading.com/">
    <meta name="og:site_name" content="Success Trading">
    <meta name="og:locale" content="pt_BR">
    <meta name="og:video" content="http://sucessotrading.com/img/sucesso_es.mp4">
    <meta name="og:type" content="website">

    <title>@yield('title')</title>

</head>

<body>
    <header style = "height: 100%">
        <nav id="id_navbar" class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar ">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-ico">
                        <i class="material-icons">
                            menu
                        </i>
                    </span>
                </button>
                <div class="collapse navbar-collapse justify-content-center " id="navbarSupportedContent">
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link home scroll active" href="#home">Home</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link product scroll" href="#product">Produto</a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link support scroll" href="#support">Suporte</a>
                        </li> 
                        <!-- <li class="nav-item ">
                            <a class="nav-link" href="#plansModal">Preços</a>
                        </li> -->
                        <li class="nav-item ">
                            <a class="nav-link plans scroll" href="#plans" data-toggle="modal"
                                data-target="#plansModal">Plano de Negócio</a>
                        </li>
                        <li class="nav-item">
                            <a id = "hera" class="login" target="_blank" href="https://sucessotrading.com/hera/?i=pt">
                                <button type="button" class="btn btn-success">Login</button>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="home">
        <div class="col-lg-12 col-md-12 col-sm-12 col-logo">
            <div id="id_detail_logo" class="d-flex flex-column align-items-center box-home">
                <img id="id_logo" class="logo" src="img/logo.svg">
                <h5 id="title">O <strong>sucesso financeiro</strong> <br> nas <strong>suas mãos</strong></h5>
                <br>
                <a href="#plans" data-toggle="modal" data-target="#plansModal">
                    <button id="btnPlans" type="button" class="btn btn-success btn-lg">
                        Conheça aqui nossos planos
                    </button>
                </a>
            </div>
            </div>
        </div>
        <!--<div class="col-lg-6 col-md-6 col-sm-12 col-register-user">
            
        </div> -->       
</div>
    </header>

resources/views/layout/template.blade.php
	@include('layout._includes.top')
	@yield('content')
	@include('layout._includes.footer')

resources/views/main/_includes/about.blade.php
<div class="container">
<div class="about">
                    <div id="about" class="row">
                        <div class="col-lg-6 col-md-6">
                            <hr>
                            <h3>SOBRE</h3>
                            <h2>NÓS</h2>
                            <p id="text-about">Sucesso Trading é uma empresa especializada em locação de criptomoedas
                                com foco no rendimento de capital com transparência, agilidade e eficácia a todo usuário
                                que utiliza o serviço de locação de nossas moedas (SCN).</p>

                        </div>
                        <div class="col-lg-6 col-md-6 coin">
                            <img class="img-fluid" src="img/03-moeda.png">
                        </div>
                    </div>

                    <div class="row cards-about">
                        <div class="cols-about col-lg-4 col-md-4 col-sm-12 col-12">
                            <div id="mission" class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-lg-2 col-md-2 col-sm-2">
                                            <img src="img/03-missao.png" class="align-self-end mr-3 card-img-top"
                                                alt="Missão - Sucesso">
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-10">
                                            <h5 class="card-title">MISSÃO</h5>
                                        </div>
                                    </div>

                                    <p class="card-text">Oferecer com excelência aos nossos clientes o
                                        serviço de trade e auxiliá-los a alcançar o sucesso financeiro, de maneira
                                        íntegra,
                                        efetiva e
                                        progressiva.</p>
                                </div>
                            </div>
                        </div>
                        <div class="cols-about col-lg-4 col-md-4 col-sm-12 col-12">
                            <div id="view" class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-lg-2 col-md-2 col-sm-2">
                                            <img src="img/03-visao.png" class="card-img-top" alt="...">
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-10">
                                            <h5 class="card-title">VISÃO</h5>
                                        </div>
                                    </div>
                                    <p class="card-text">Oferecer com excelência aos nossos clientes o serviço de trade
                                        e
                                        auxiliá-los a alcançar o sucesso financeiro, de maneira íntegra, efetiva e
                                        progressiva.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="cols-about col-lg-4 col-md-4 col-sm-12 col-12">
                            <div id="values" class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-lg-2 col-md-2 col-sm-2">
                                            <img src="img/03-valores.png" class="card-img-top" alt="...">
                                        </div>
                                        <div class="col-lg-10 col-md-10 col-sm-10">
                                            <h5 class="card-title">VALORES</h5>
                                        </div>
                                    </div>
                                    <p class="card-text">Transparência; Segurança para o cliente; Prosperidade; Sucesso
                                        financeiro
                                        Tecnologia; O novo tesouro Simplicidade; Desburocratizando o mercado financeiro
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
</div>

resources/views/main/_includes/contact.blade.php
<div id="support" class="container center-block container-contact">
    <div class="row pt-5">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="title-contact">
                <hr>
                <h3>ENTRE EM</h3>
                <h2>CONTATO</h2>
                <ul class="info-contact pt-2"> 
                    <li>
                        <a href="https://www.instagram.com/sucessotrading/" target="_blank"><img class="img-fluid mr-2" src="/img/icons/insta.png">@sucessotrading</a>
                    </li>
                    <li>
                        <a href="https://api.whatsapp.com/send?phone=5592991049702&text=Ola%20gra%C3%A7as%20pelo%20seu%20contato%20como%20posso%20le%20ajudar" target="_blank">
                        <img class="img-fluid mr-2" src="/img/icons/wpp.png">+55 92 9204-9702</a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/sucessotradingusa/" target="_blank"><img class="img-fluid mr-2" src="/img/icons/insta.png">@sucessotradingusa</a>
                    </li>
                    <li>
                        <a href="https://api.whatsapp.com/send?phone=13055193817&text=En%20que%20le%20podemos%20servir%20" target="_blank">
                        <img class="img-fluid mr-2" src="/img/icons/wpp.png">+1 (305) 519-3817</a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/sucessotrading/" target="_blank"><img class="img-fluid mr-2" src="/img/icons/fb.png">Sucesso Trading</a>
                    </li>
                </ul> 
            </div>
        </div>
            <div class="col-lg-6 col-md-6 col-sm-12 contact">
                <div class="row">
                    <div class="col-form">
                        <form action="{{ route('contact.send')}}" method="POST">
                            @include('partials.messages')
                            {{ csrf_field() }}
                            <div class="form-group">
                                <input name="name" type="text" class="form-control" id="inputName" aria-describedby="emailHelp"
                                    placeholder="Nome">
                            </div>
                            <div class="form-group">
                                <input name="email" type="email" class="form-control" id="inputEmail" aria-describedby="emailHelp"
                                    placeholder="Email">
                            </div>
                            <div class="form-group">
                                <input name="subject" type="text" class="form-control" id="inputSubject" placeholder="Assunto">
                            </div>
                            <div class="form-group">
                                <textarea name="bodyMessage" id="textarea" class="form-control" placeholder="Sua mensagem"
                                    rows="3"></textarea>
                            </div>
                            <!-- <div class="form-group">
                               <div class="col-md-6 offset-md-4">
                                   <div class="g-recaptcha" data-sitekey="{{ env('CAPTCHA_KEY') }}"></div>
                                    @if($errors->has('g-recaptcha-response'))
                                    <span class="invalid-feedback" style="display:block">
                                        <strong>{{$errors->first('g-recaptcha-response')}}</strong>    
                                    </span>
                                    @endif
                                </div>
                            </div> -->
                            <div class="text-center div_btn-contact">
                                <button type="submit" class="btn">Enviar</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            </div>
        </div>
        <script src="https://www.google.com/recaptcha/api.js?render=_reCAPTCHA_site_key"></script>

resources/views/main/_includes/scn.blade.php
<div class="text-left scn" id="product">
                <div class="container">
                    <div class="row">
                        <div class="col-video col-lg-6 col-md-6 col-md-12">
                            <video id="videoSucesso" controls>
                                <source id="mp4_src" src="img/sucesso_pt.mp4" type="video/mp4">
                            </video>
                        </div>
                        <div class="col-coin col-lg-6 col-md-6 col-md-12">
                            <hr>
                            <div class="pl-2 pt-1">
                                <h3>CRIPTOMOEDA PRÓPRIA</h3>
                                <h1>SUCESSO COIN - SCN</h1>
                                <p class="text-left scn-detail">
                                    SCN é uma criptomoeda nova, criada pela Sucesso Trading com a intenção de
                                    facilitar ainda mais as suas transações em operações descentralizadas,
                                    utilizando a tecnologia de segurança Blockchain, ou seja, tornando-as
                                    ágeis e menos sujeitas a golpes e fraudes.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

resources/views/partials/messages.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Errors</strong>
        <ul>
            @foreach($errors->all() as $erros)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/prices/price.blade.php
@extends('layout.template')

@section('title','Sucesso Trading')

@section('content') 
<!--Main Layout-->
<div class="bg">

    <div class="container text-center" style="width: auto;">
    <h1 class="great-profit" style="margin: 200px 0 50px 0">Ótimos rendimentos com criptomoedas</h1>
    <h6 class="weekly-income">Tenha um rendimento semanal de 3% e anual de 156%</h6>
        <img class="teste" style="width: 50%;margin: 50px 30% 50px 30%;padding:0 auto;" src="img/pt/rendimentos.png">
        <form class="text-center mb-4"> 
            <input type="button" class="btn btn-success btn-lg btn-prices" value="Cadastre-se e lucre agora" onClick="history.go(-1)"> 
        </form>
    </div>
</div>
<!---end bg-main-->    
@endsection

resources/views/users/create_users.blade.php
<div id="id-form-create-user" class="form-create-user">
    <div class="border-left-cad">
        <h3 id="register-text" class="text-cadastre-se">Cadastre-se agora</h3>
        <p id="register-description">E converse com um dos nossos especialistas em Manaus:</p>
    </div>
    
                <form action="{{ route('users.store') }}" method="POST" 
                    <!-- @include('partials.messages') -->
                    @csrf <!-- {{ csrf_field() }} -->
                    @method('POST')
                    <div class="form-group">
                        <label id="name-user">Nome:</label>
                        <input name="name" type="text" class="form-control" aria-describedby="aName">
                    </div>
                    <div class="form-group">
                        <label id="phone-user">Seu celular:</label>
                        <div class="media">
                            <div class="media-body">
                                <input name="phone" type="number" class="form-control" aria-describedby="aPhone">
                            </div>
                        </div>
                        
                         </div>
                    <div class="form-group">
                        <label id="email-user">Email:</label>
                        <input name="email" type="email" class="form-control" aria-describedby="aEmail">
                    </div>

                    <div class="text-right btnRegister">
                        <button  type="submit" class="btn btn-success btn-lg">
                            Register
                        </button>
                    </div>
                </form>
            </div>

resources/views/users/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
<div class="jumbotron" style="margin-top: 50px;">
    <h1 class="display-1">Registration successfully created!</h1>
    <p class="lead">Sucesso Trading thanks you for your visit!</p>
    <hr class="my-4">
    <form> 
        <input type="button" class="btn btn-success btn-lg" value="Back" onClick="history.go(-1)"> 
    </form>
</div>
</div>
   
</body>
</html>